# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on: [push, pull_request]

name: cover

jobs:
  cover:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      NOT_CRAN: true

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr, any::rstudioapi
          needs: coverage

      - name: Test coverage
        run: |
          out <- covr::zero_coverage(covr::package_coverage())
          out <- out[!grepl("^src", out$filename),, drop = FALSE]
          print(out)
          if (nrow(out)) stop("some lines not covered by tests")
        shell: Rscript {0}
